name: linux-tests
services:
  swift600:
    build:
      context: .
      dockerfile: swift600.Dockerfile
    working_dir: /app
    entrypoint: swift test

  swift601:
    build:
      context: .
      dockerfile: swift601.Dockerfile
    working_dir: /app
    entrypoint: swift test
